# Generated by Django 5.2.15 on 2026-06-16 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_venue_verification_status'),
        ('events', '0005_add_event_organizer_fields'),
    ]

    operations = [
    ]
