# Generated by Django 5.2.15 on 2026-06-17 00:01

from django.db import migrations


def _normalize_url(url):
    """Lowercase scheme+host and strip a trailing slash. Returns "" for blank."""
    from urllib.parse import urlparse, urlunparse

    if not url:
        return ""
    parsed = urlparse(url.strip())
    normalized = parsed._replace(
        scheme=parsed.scheme.lower(),
        netloc=parsed.netloc.lower(),
    )
    return urlunparse(normalized).rstrip("/")


def link_event_organizer(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Organizer = apps.get_model("events", "Organizer")

    # Build {normalized_website: organizer_pk}. If two organizers normalize to the
    # same website, the last one wins — acceptable; URL collisions are rare here.
    website_to_pk = {}
    for org in Organizer.objects.all():
        key = _normalize_url(org.website)
        if key:
            website_to_pk[key] = org.pk

    url_matched = 0
    name_matched = 0
    unmatched = 0

    # Pass 1 — URL match.
    pass1_updates = []
    still_unlinked = []
    for event in Event.objects.filter(organizer_ref__isnull=True):
        key = _normalize_url(event.organizer_url)
        pk = website_to_pk.get(key) if key else None
        if pk is not None:
            event.organizer_ref_id = pk
            pass1_updates.append(event)
            url_matched += 1
        else:
            still_unlinked.append(event)

    if pass1_updates:
        Event.objects.bulk_update(pass1_updates, ["organizer_ref"], batch_size=500)

    # Pass 2 — case-insensitive unambiguous name match.
    pass2_updates = []
    for event in still_unlinked:
        name = (event.organizer or "").strip()
        if not name:
            unmatched += 1
            continue
        matches = list(Organizer.objects.filter(name__iexact=name).values_list("pk", flat=True))
        if len(matches) == 1:
            event.organizer_ref_id = matches[0]
            pass2_updates.append(event)
            name_matched += 1
        else:
            # Ambiguous (>1) or no match: leave organizer_ref None.
            unmatched += 1

    if pass2_updates:
        Event.objects.bulk_update(pass2_updates, ["organizer_ref"], batch_size=500)

    print(
        f"link_event_organizer: URL-matched={url_matched}, "
        f"name-matched={name_matched}, unmatched={unmatched}"
    )


def unlink_event_organizer(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    Event.objects.filter(organizer_ref__isnull=False).update(organizer_ref_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_organizer_ref'),
    ]

    operations = [
        migrations.RunPython(link_event_organizer, unlink_event_organizer),
    ]
