# Generated by Django 6.0.6 on 2026-06-16 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='Identifier of the scraper/source this record came from.', max_length=120)),
                ('source_url', models.URLField(blank=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('price', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, help_text='Identifier of the scraper/source this record came from.', max_length=120)),
                ('source_url', models.URLField(blank=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.venue')),
            ],
            options={
                'ordering': ['starts_at', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('source', 'external_id'), name='unique_source_external_id')],
            },
        ),
    ]
