# Generated by Django 6.0.6 on 2026-06-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='place_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(condition=models.Q(('place_id__gt', '')), fields=('source', 'place_id'), name='unique_venue_source_place_id'),
        ),
    ]
