# Generated by Django 6.0.6 on 2026-06-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_venue_place_id_venue_unique_venue_source_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='amenities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='venue',
            name='price_level',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='venue',
            name='primary_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='venue',
            name='primary_type_display',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='venue',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
