# Generated by Django 6.0.6 on 2026-06-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_venue_about_venue_amenities_venue_price_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified — events venue'), ('rejected', 'Rejected — not an events venue')], db_index=True, default='pending', help_text='Manual admin review state for whether this is a real events venue.', max_length=20),
        ),
    ]
