# Generated by Django 6.0.6 on 2026-06-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_increase_url_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
