# Generated by Django 5.2.15 on 2026-06-17 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.organizer'),
        ),
    ]
