# Generated by Django 6.0.6 on 2026-06-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_link_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='agent_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
