# Generated by Django 5.2.15 on 2026-06-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_scraperrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperrun',
            name='pid',
            field=models.PositiveIntegerField(blank=True, help_text='OS PID of the worker subprocess; null for queued/pre-subprocess rows.', null=True),
        ),
        migrations.AlterField(
            model_name='scraperrun',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20),
        ),
    ]
