# Generated by Django 6.0.6 on 2026-06-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_agent_categories'),
        ('events', '0012_scraperrun_unique_active_constraint'),
    ]

    operations = [
    ]
