# Generated by Django 5.2.15 on 2026-06-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_agent_categories'),
        ('events', '0012_scraperrun_unique_active_constraint'),
    ]

    operations = [
    ]
