# Generated by Django 5.2.15 on 2026-06-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_merge_20260617_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='agents_primary_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
