# Generated by Django 5.2.15 on 2026-06-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_merge_20260617_0814'),
        ('events', '0014_add_agents_primary_types_to_venue'),
    ]

    operations = [
    ]
