# Generated by Django 5.2.15 on 2026-06-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_merge_20260617_0821'),
        ('events', '0015_merge_20260617_0822'),
    ]

    operations = [
    ]
