# Generated by Django 5.2.15 on 2026-06-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_merge_20260617_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='enriched_at',
            field=models.DateTimeField(blank=True, help_text='When enrichment was last run against an external API for this organizer.', null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='enrichment_source',
            field=models.CharField(blank=True, help_text="Comma-separated list of APIs that contributed enrichment data, e.g. 'diffbot,hunter'.", max_length=120),
        ),
    ]
