# Generated by Django 5.2.15 on 2026-06-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_organizer_enrichment_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='enriched_at',
            field=models.DateTimeField(blank=True, help_text='When the crawler last ran enrichment for this organizer.', null=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='enrichment_source',
            field=models.CharField(blank=True, help_text="How enrichment data was gathered, e.g. 'crawler' or 'skipped_no_website'.", max_length=120),
        ),
    ]
