# Generated by Django 6.0.6 on 2026-06-19 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_scraperrun_log_output'),
        ('events', '0019_searchquery'),
    ]

    operations = [
    ]
