# Generated by Django 5.2.15 on 2026-06-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_merge_0019_scraperrun_log_output_0019_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
