# Generated by Django 5.2.15 on 2026-06-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_add_registration_url_to_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ['query']},
        ),
        migrations.RemoveConstraint(
            model_name='searchquery',
            name='unique_source_query',
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Scraper key that found this query, if any. Legacy field.', max_length=120),
        ),
        migrations.AddConstraint(
            model_name='searchquery',
            constraint=models.UniqueConstraint(fields=('query',), name='unique_query'),
        ),
    ]
