# Generated by Django 5.2.15 on 2026-06-23 00:21

from django.db import migrations, models


def _dedup_search_queries(apps, schema_editor):
    SearchQuery = apps.get_model("events", "SearchQuery")
    Event = apps.get_model("events", "Event")
    seen = {}
    for sq in SearchQuery.objects.order_by("pk"):
        if sq.query in seen:
            # Reassign any events pointing at this duplicate to the canonical row
            # before deletion so FK integrity is preserved.
            Event.objects.filter(search_query_id=sq.pk).update(search_query_id=seen[sq.query])
            sq.delete()
        else:
            seen[sq.query] = sq.pk


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_add_registration_url_to_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ['query']},
        ),
        migrations.RemoveConstraint(
            model_name='searchquery',
            name='unique_source_query',
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Scraper key that found this query, if any. Legacy field.', max_length=120),
        ),
        migrations.RunPython(_dedup_search_queries, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='searchquery',
            constraint=models.UniqueConstraint(fields=('query',), name='unique_query'),
        ),
    ]
