# Generated by Django 6.0.6 on 2026-06-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_decouple_search_query_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='post_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='raw_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
