# Generated by Django 6.0.6 on 2026-06-23 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_decouple_search_query_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_note', to='events.event')),
                ('organizer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_note', to='events.organizer')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('event__isnull', False), ('organizer__isnull', True)), models.Q(('event__isnull', True), ('organizer__isnull', False)), _connector='OR'), name='tracker_note_exactly_one_entity')],
            },
        ),
    ]
