# Generated by Django 5.2.15 on 2026-06-24 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_trackernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandwidthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=120)),
                ('proxy_type', models.CharField(choices=[('dataimpulse', 'DataImpulse'), ('free', 'Free proxy')], db_index=True, max_length=40)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scraper_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bandwidth_logs', to='events.scraperrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
