# Generated by Django 6.0.6 on 2026-06-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_add_raw_text_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enriched_at',
            field=models.DateTimeField(blank=True, help_text='Set when the Ollama LLM successfully structured this FB post.', null=True),
        ),
    ]
