# Generated by Django 6.0.7 on 2026-07-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_merge_20260625'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='crm_pushed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last time this event was successfully pushed to the CRM. Null = never pushed. Used to filter incremental push.', null=True),
        ),
    ]
