# Generated by Django 5.2.15 on 2026-06-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_merge_20260625'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='pushed_to_crm_at',
            field=models.DateTimeField(blank=True, help_text='When this organizer was last successfully pushed to the CRM ingest endpoint.', null=True),
        ),
    ]
