# Generated by Django 6.0.7 on 2026-07-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_add_event_crm_pushed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperrun',
            name='discord_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
