# Generated by Django 6.0.7 on 2026-07-17 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_scraperrun_discord_message_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trackernote',
            name='tracker_note_exactly_one_entity',
        ),
        migrations.DeleteModel(
            name='TrackerNote',
        ),
    ]
