# Generated by Django 6.0.7 on 2026-07-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_remove_trackernote_tracker_note_exactly_one_entity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraper_keys', models.CharField(blank=True, help_text='Comma-separated scraper keys. Mirrors SCRAPER_KEYS env var.', max_length=2000)),
                ('scraper_interval', models.CharField(blank=True, help_text='Round interval. Format: 6h / 30m / 3600s. Mirrors SCRAPER_INTERVAL.', max_length=20)),
                ('push_interval', models.CharField(blank=True, help_text='CRM push interval. Format: 1h / 30m. Mirrors PUSH_INTERVAL.', max_length=20)),
                ('scraper_timeout', models.CharField(blank=True, help_text='Per-scraper timeout. Format: 90m / 3600s. Mirrors SCRAPER_TIMEOUT.', max_length=20)),
                ('per_key_intervals', models.JSONField(blank=True, default=dict, help_text='Per-scraper interval overrides. {"luma": "24h"}. Mirrors SCRAPER_INTERVAL_<KEY> env vars.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, help_text='Email of the CRM user who last updated this record.', max_length=255)),
            ],
            options={
                'verbose_name': 'Scraper config',
                'verbose_name_plural': 'Scraper config',
            },
        ),
    ]
